### ISSUE TITLE
Animation speed correction

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#134]
Mobiles in the XNA client animate at one loop per tile moved. The legacy client animates at least some - perhaps all - mobiles slower. There’s likely some file out there that handles information on the animation speeds for mobiles. I think it is used, at least in part, by the AnimatingEffect class.

**Comment by fdsprod** [comment]
It appears to me that in the legacy client when walking or running, 1/2 of the animation is played per tile.  If that is what is happening, it should be fine.  It may appear slightly faster because UltimaXNA is running at a solid 60+ frames per second, where as the client is running at roughly 15, causing the animation to look slower, or possibly frame skipping due to frame catch-up.

**Comment by robertdeclaux** [comment]
Hello Zane i want to know something, I want to restrict the other builds of
UltimaXNA from playing on my server, just a build by me and every player
uses this one. How can we do this? Can we add somespecial packets or...?

2015-04-23 19:11 GMT+03:00 Jeff Boulanger <notifications@github.com>:

**Comment by fdsprod** [comment]
Doing this would be easily circumvented.  Anyone with any programming
knowledge could just look at this new packet and implement it on any other
version of the client as well.   With the client being open source, and C#
being easy to decompile, you are kind of out of luck when it comes to doing
something like this.

**Comment by ZaneDubya** [comment]
Jeff is responding to @robertdeclaux: Hello Zane i want to know something, I want to restrict the other builds of UltimaXNA from playing on my server, just a build by me and every player uses this one. How can we do this? Can we add somespecial packets or...?

I agree 100% with what Jeff wrote. You can make it more difficult for people to use something other than one specific client, but you will never be able to make it impossible. And all it would take is one person to crack your security feature and distribute the modified client.

**Comment by naggie** [comment]
Doesn't runUO detect running/walking at odd speeds and kick the client?

**Comment by fdsprod** [comment]
@naggie No, RunUO uses packet throttling to ensure that each player can only move so many tiles per second.  Basically when you move, the client sends a move request and starts the movement animation to the next tile.  The server can then tell the client that it acknowledge or rejects the request.  On reject, the client moves the player back to the tile prior to the reject.  This is what causes rubber banding.   So in RunUO, the accept packet is throttled based on time so that not only will the client not receive a acknowlegement at a proper movement rate, the server itself makes sure the player is not moving at a faster than normal rate.

**Comment by ZaneDubya** [comment]
@naggie Are you talking about rate of movement or rate of animation? I believe that entities in UltimaXNA move at the same rate of movement as the default legacy client. However, the rate of animation is different. That's what I'm hoping to fix with this issue.

**Comment by naggie** [comment]
Ah ok, thanks for the explanations.

**Comment by ZaneDubya** [comment]
I think I have this fixed as of 2c985957e2aa35057100b8472a38ae39850baddd.

**Comment by ZaneDubya** [comment]
Closing as complete.
