### ISSUE TITLE
Items display different graphics in stacks.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#146]
UltimaXNA has support for stacks of coins, I believe: one coin looks different than a few coins, which look different from a huge pile of coins.

There are many such items that should display different graphics when they are stacked. UltimaXNA should implement each of these.

Question for this issue:
- How are stackable graphics implemented? Are they hardcoded or as a item flag?
- Do all stackable objects have three graphics (one, few, many)?

**Comment by Vodacek** [comment]
Unfortunatelly I think that this is also hardcoded fuctionality.
 

---

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya @Vodacek

Actually there are two types of stackable
- Stackable items, where if amount is more than one, ItemID is not changed, but two same IDs are show with offset. So it looks like two items next to each other. This is done by tiledata flag and offset value. Reagents, ores, ingots, for example. + Stackable = true; in item script :-)
- Stackable items, where more different  ItemIDs are shown based on amount. You also need to set stackable flag, but ItemID change is either hardcoded or, which i believe, in other tiledata flags. Also possible to change IDs by server script based on amount.

If flag in tiledata is not set, you cannot split stacked items by dragging them, because client will not show "select amount " gump.

**Comment by fdsprod** [comment]
@ZaneDubya tiledata.mul contains stack offset information.

Here are the scenarios for dropped items.

Ground : send packet 0x08 with 0xFFFFFFFF as the parent container (this means ground)
Mobile: send 0x08 with mobile serial as parent container.
Target == container as item(not gump): 0x08 with serial as parent container.
Target == non-container: 0x08 with serial as parent container.
Target == gump container: 0x088 with serial as parent container and x/y coords.  

The server will reply with accept drop and send a new world item packet to update the id if needed.   The only items you may need to render yourself is if the amount of the item is > 1 and the tiledata.nul for that item has a stack offset.

I believe this should be sufficient.

0x08 packet details:
http://docs.polserver.com/packets/index.php?Packet=0x08

**Comment by ZaneDubya** [comment]
Implemented in 2c985957e2aa35057100b8472a38ae39850baddd.
