### ISSUE TITLE
Hued Items and light Color are darker

### ISSUE THREAD

**Issue by Xen85** [ZaneDubya/UltimaXNA#148]
I tried latest version in a custom shard, i saw that hued color and light color were darker than usual.
I tried to disable the hued coloration in effect ( .fx ) file and all were right. I think hues management has some issue.

If i try to translate to MonoGame, all the project works but light colors and hues are black.
I think it means there is a bug somewhere in IsometricWorld.fx about hues 

you can follow this discussion because a member of MonoGame team were interested in helping with porting https://www.servuo.com/threads/ultimaxna-translated-to-monogame-3-4.2886/

**Comment by ZaneDubya** [comment]
Would you please post images showing an example of the expected and observed colors? Please also post the item id and hue id so I can replicate it on this end.

**Comment by Xen85** [comment]
ORIGINAL : 

https://mega.co.nz/#!31oUQaqT!CzjUHJ_F8VMgeZQ_-7qLJU2HL6OOBWqxANC3glr6aMo

https://mega.co.nz/#!qwwyHCqZ!uPg6yQoxsdTL0wj2-3UhYPvp79lXqm6hbgOjw9fTor8

https://mega.co.nz/#!zgIwnAiS!5fmOZ0MHCGctnDmFVTmlVbTPQhT8TM-jNY_XEb1BLKY

https://mega.co.nz/#!DhZxnAxR!tuTAN_sYAENz7DGut7_g5hhaWcvjjYEWHKaH477ddBk

https://mega.co.nz/#!TthGWQII!bOK00jaX4pDVdGnSBLJy1RbAwdWW2FATiaJWFv1-TcY

MonoGame (no hue)

https://mega.co.nz/#!ugYGjIYS!thytKcCod67rO2q_uGlgfY79Do2AjGvdVb_NJR4hkb8

https://mega.co.nz/#!P95kjTxT!pl_V1OAhghgTk1Xs078P8tN9CIWZ0bklKo-IgNJbkIY

XNA (hued)

https://mega.co.nz/#!a9BDkCLT!lUdn0FB_ml9Fr7M-vMILNmPxQvNHNeC26VPFDjC4z7c

https://mega.co.nz/#!y4ZSgQAQ!VSOOJ9gBLdW9sQw3VuhfEqRA_EQE0zHVQjIY44h5mq0

https://mega.co.nz/#!DlxmlQDQ!OvXd_v5PH8IMa_r9-_US-eIh0si0DCYJC8f4BCupDm8

https://mega.co.nz/#!P95kjTxT!pl_V1OAhghgTk1Xs078P8tN9CIWZ0bklKo-IgNJbkIY

I can't see the original hue °°"

**Comment by ZaneDubya** [comment]
@Xen85 As I noted in the servuo thread you posted to, I'm not interested in troubleshooting a monogame port. Please restrict your bug reports to the xna client. :)

There is a ton going on in your images and they're taken from multiple locations. I can't tell exactly what you want me to look at, and I can't replicate your bug unless you include more information.

Please indicate a specific test case, with one specific item and hue, with screenshots in the legacy client and in the xna client from the same location. Include the item id and hue id. It would also be really helpful if you took these pictures from the default world map - somewhere in Britain that I could go myself. Also, please drag the images into the github text editor instead of hosting on mega.co.nz. Thanks!

**Comment by ZaneDubya** [comment]
@Xen85 can you create a situation which would replicate the bug you found?

**Comment by ZaneDubya** [comment]
Closing as unable to replicate. @Xen85, if you can create a test case, I would love to address this. Just post here and re-open (or I'll reopen if you can't).
