### ISSUE TITLE
Context menus should be modal.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#240]
original text removed, see Eskymak's description for the bug addressed by this issue.

**Comment by PatrikSamuelTauchim** [comment]
When you move cursor out of context menu, it is closed immediately. This is not expected behavour, can you look at this?. :-)

When entity is moving durring context menu is open, it shoud stay opened on location it was originaly opened, otherwise it will be complicated to use context menus at moving entities.

**Comment by ZaneDubya** [comment]
@Eskymak When should the context menu be closed? Are they modal (open context menu causes all other controls to ignore input; but a click anywhere outside of the context menu would cause it to close?)

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya Yes, It should be closed if you click outside of it. In original client, it stays open even if you walk away (by using keyboard) from object, from which it was opened.

**Comment by ZaneDubya** [comment]
Closing as implemented.
