### ISSUE TITLE
SpellbookGump is called twice randomly and draws too many spells

### ISSUE THREAD

**Issue by orsi** [ZaneDubya/UltimaXNA#367]
I'm not familiar with the network code that is calling this function twice, so I hope someone can figure this out. I think this might be a threading or some kind of asynchronous issue.

Each spellbook draws correctly when it is opened for the first time. However, when opening the same spellbook for the second time and every time after, it begins to draw twice.

> Correctly draws spells in spell index
> ![image](https://cloud.githubusercontent.com/assets/7156655/9978916/15d33df2-5f1e-11e5-8460-4af09b6f847d.png)
> 
> Begins to draw spells twice in the spell index
> ![image](https://cloud.githubusercontent.com/assets/7156655/9978918/45180cbe-5f1e-11e5-92c5-ec02f9a30cfa.png)

I've narrowed down why it is doing this to WorldClient.cs. When each spellbook opens for the first time, the program first calls ReceiveContainer(IRecvPacket packet), second ReceiveGeneralInfo(IRecvPacket packet), then SpellbookGump.CreateMageryGumplings() only once.

However, for some reason after a spellbook is closed and then reopened, it starts calling ReceiveContainer(IRecvPacket packet), SpellbookGump.CreateMageryGumplings(), ReceiveGeneralInfo(IRecvPacket packet), and then SpellbookGump.CreateMageryGumplings() for the second time.

> Code execution when it draws correctly:
> ![image](https://cloud.githubusercontent.com/assets/7156655/9978971/08993914-5f20-11e5-935e-10a283fef8fd.png)
> ![image](https://cloud.githubusercontent.com/assets/7156655/9978973/10334ed0-5f20-11e5-92a2-5855a83dc793.png)
> ![image](https://cloud.githubusercontent.com/assets/7156655/9978974/1465689e-5f20-11e5-908c-0cbe00608d81.png)
> 
> Code execution when it draws incorrectly:
> ![image](https://cloud.githubusercontent.com/assets/7156655/9978950/a3c6bebc-5f1f-11e5-9681-3a7ee99f2ad9.png)
> ![image](https://cloud.githubusercontent.com/assets/7156655/9978954/aefc78c6-5f1f-11e5-901e-c25fdd092181.png)
> ![image](https://cloud.githubusercontent.com/assets/7156655/9978964/bb302f70-5f1f-11e5-815f-448dde5b0e1c.png)
> ![image](https://cloud.githubusercontent.com/assets/7156655/9978965/c12cb510-5f1f-11e5-80eb-a40e7b72113e.png)

**Comment by ZaneDubya** [comment]
Thank you for reporting this bug; I'll take a look at it.

**Comment by ZaneDubya** [comment]
Fixed in 73395f3. The spells were being drawn twice because m_SpellList was not being cleared in CreateMageryGumplings().

The underlying issue - that the spell book was being updated - is caused by RunUO always sending the spell book contents whenever it is opened. The spell book entity would then raise the OnEntityUpdated event, which was hooked by the SpellbookGump. Because m_SpellList is now cleared, this would not cause the spell book to be double-populated. However, it would cause the gumplings to be drawn twice, which would cause a performance hit. I've added code so that a spell book only rates the OnEntityUpdated event when its contents are actually changed. :)

Thanks for your work on this issue @jorsi - looks great!
