### ISSUE TITLE
Dragging an Object to/in your Backpack Makes the Object Disappear 

### ISSUE THREAD

**Issue by greeduomacro** [ZaneDubya/UltimaXNA#412]
If you drag an object with left click and then drop the object in your backpack then the object, regardless of what it is, simply disappears and requires you to log out and log back in to be able to see/interact with the object once again.

**Comment by ghost** [comment]
Seems that object only disappears when adding to container, cause of wrong container id sent by addSingleItem packet. I haven't understand it yet

**Comment by ghost** [comment]
Yah! Finally, get on with it! The trouble was the versioning, on my machine uxna gets wrong client version - 0.0.0.0.

**Comment by ZaneDubya** [comment]
I believe I've fixed the version checking issue, which may have fixed this issue as well.

**Comment by ZaneDubya** [comment]
@Pishka @greeduomacro I'm pretty sure I've fixed this! The problem was loading the version from old versions of the client - some did not have the version set, so it reported as 0.0.0.0. I've implemented new version checking logic, and this should not be an issue any longer. Please let me know if this is still an issue.
