### ISSUE TITLE
Render priorities (RC1)

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#97]
![ekran goruntusu 21](https://cloud.githubusercontent.com/assets/11157985/6989619/8dccfaba-da66-11e4-9358-5f7fbcfcddc4.png)
![ekran goruntusu 22](https://cloud.githubusercontent.com/assets/11157985/6989620/8dd202d0-da66-11e4-9dd0-15cedad79390.png)
![ekran goruntusu 23](https://cloud.githubusercontent.com/assets/11157985/6989621/8dd5229e-da66-11e4-8f52-d331a0737fef.png)

**Comment by ZaneDubya** [comment]
There will always be some sorting and rendering priority problems.

I believe pics 1 and 2 will be fixed by removing the `+1` from the end of Line 137 in UltimaEntitties\EntityViews\GroundView.cs. But this will cause certain water-coastline statics to be rendered beneath land tiles. Perhaps all water-coastline statics should have their sort value incremented by 1 instead?

Fixing Pic 3 would require a new deferred rendering strategy.

**Comment by ZaneDubya** [comment]
Pic 1 and 2 addressed in d155dd1e13d13ae2d33736e4adf8f78cd1e6f4bb. Do not intend to fix "error" in Pic 3 - it's very similar to legacy client priority errors :)
